import sqlite3 as db

con=db.connect("universitate.db")

kursors=con.cursor()
kursors.execute('''select Studentu_ID from Studenti''')

izv_Sudenta_ID=kursors.fetchall()
Studenta_ID="STU"+str(len(izv_Sudenta_ID)+1)

kursors.execute('''select Profesora_ID from Profesori''')

izv_Prof_ID=kursors.fetchall()
Profesora_ID="PRO"+str(len(izv_Prof_ID)+1)

kursors.execute('''select Kursa_ID from Kursi''')

izv_Kursa_ID=kursors.fetchall()
Kursa_ID="KUR"+str(len(izv_Kursa_ID)+1)

Studenta_Vards=input("Ievadi Studenta Vārdu:")
Studenta_Spec=input("Ievadi Studenta Specialitāti:")
Absolv_Gads=input("Ievadi Studenta Absolvēšanas gadu:")
kursors.execute('''insert or ignore into Studenti values(?,?,?,?);''',(Kursa_ID,Studenta_Vards,Studenta_Spec,Absolv_Gads))
con.commit()

Profesora_Vards=input("Ievadi Profesora Vārdu:")
Profesora_Katedra=input("Ievadi Profesora Katedru:")
Profesora_DarbaVieta=input("Ievadi Profesora Darba Vietu:")
kursors.execute('''insert or ignore into Profesori values(?,?,?,?);''',(Profesora_ID,Profesora_Vards,Profesora_Katedra,Profesora_DarbaVieta))
con.commit()

Kursa_Nosaukums=input("Ievadi Kursa Nosaukumu:")
Kreditpunkti=input("Ievadi Kredītpunktus:")
Prieksnosacijumi=input("Ievadi Priekšnosacijums:")
StudentaK_ID=input("Ievadi Studenta ID Kursam:")
ProfesoraK_ID=input("Ievadi Profesora ID Kursam:")
kursors.execute('''insert or ignore into Kursi values(?,?,?,?,?,?);''',(Kursa_ID,Kursa_Nosaukums,Kreditpunkti,Prieksnosacijumi,StudentaK_ID,ProfesoraK_ID))
con.commit()


kursors.execute('''select Studentu_Specialitāte from Studenti''')
Spec_izvade=kursors.fetchall()
print(Spec_izvade)
kursors.execute('''select Absolv_Gads from Studenti''')
Gad_izvade=kursors.fetchall()
print(Gad_izvade)
kursors.execute('''select Kursa_Nosaukums from Kursi''')
Kur_izvade=kursors.fetchall()
print(Kur_izvade)
kursors.execute('''select Kreditpunkti from Kursi''')
kred_izvade=kursors.fetchall()
print(kred_izvade)
kursors.execute('''select Profesora_Vards from Profesori''')
Prof_izvade=kursors.fetchall()
print(Prof_izvade)
kursors.execute('''select Profesora_Katedra from Profesori''')
Kat_izvade=kursors.fetchall()
print(Kat_izvade)
kursors.execute('''select Sum(Kreditpunkti) from Kursi''')
Skred_izvade=kursors.fetchall()
print(f"Count{Skred_izvade}")
kursors.execute('''select Min(Kreditpunkti) from Kursi''')
Mikred_izvade=kursors.fetchall()
print(f"Min{Mikred_izvade}")
kursors.execute('''select Max(Kreditpunkti) from Kursi''')
Makred_izvade=kursors.fetchall()
print(f"Max{Makred_izvade}")
kursors.execute('''select Avg(Kreditpunkti) from Kursi''')
Akred_izvade=kursors.fetchall()
print(f"Avg{Akred_izvade}")
kursors.execute('''select Count(Kreditpunkti) from Kursi''')
Ckred_izvade=kursors.fetchall()
print(f"Count{Ckred_izvade}")
con.close()